services:
  game:
    container_name: leek-ops-game
    build:
      context: .
      dockerfile: Dockerfile.prebuilt
    image: leek-ops-game:current
    restart: unless-stopped
    ports:
      - "8090:80"
